# Generated by Django 4.2.4 on 2023-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('domain', models.CharField(default='', max_length=500)),
                ('year_founded', models.IntegerField(default=0)),
                ('industry', models.CharField(default='', max_length=500)),
                ('size_range', models.CharField(default='', max_length=500)),
                ('locality', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=500)),
                ('linkdin_url', models.CharField(default='', max_length=500)),
                ('current_employee_estimate', models.IntegerField(default=0)),
                ('total_employee_estimate', models.IntegerField(default=0)),
            ],
        ),
    ]
