# Generated by Django 4.2.1 on 2023-08-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='locality',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='city',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='state',
            field=models.CharField(default='', max_length=500),
        ),
    ]
