# Generated by Django 4.2.4 on 2023-09-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_csvdata_locality_csvdata_city_csvdata_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='domain',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='linkdin_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='size_range',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='year_founded',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='csvdata',
            index=models.Index(fields=['name', 'year_founded', 'industry', 'country', 'city', 'state'], name='app_csvdata_name_32e776_idx'),
        ),
    ]
